name: todo
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  provider: ^6.0.5
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.19.0
  flutter_local_notifications: ^17.0.0
  reorderables: ^0.6.0
  flutter_slidable: ^3.0.1
  glassmorphism: ^3.0.0
  flutter_screenutil: ^5.9.0
  animations: ^2.0.8
  flutter_staggered_animations: ^1.1.1
  table_calendar: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
